export const ecosystemPartners = [
  {
    name: '百度',
    imgSrc: '/images/ecosystem/baidu.png',
    width: 320,
    height: 100,
  },
  {
    name: '联想',
    imgSrc: '/images/ecosystem/lenovo.png',
    width: 311,
    height: 100,
  },
  {
    name: '腾讯',
    imgSrc: '/images/ecosystem/tencent.png',
    width: 744,
    height: 100,
  },
  {
    name: '小米',
    imgSrc: '/images/ecosystem/xiaomi.png',
    width: 100,
    height: 100,
  },
  {
    name: '金山',
    imgSrc: '/images/ecosystem/kingsoft.png',
    width: 256,
    height: 100,
  },
  {
    name: 'fengping',
    imgSrc: '/images/ecosystem/fengping.png',
    width: 100,
    height: 100,
  },
  {
    name: 'xing',
    imgSrc: '/images/ecosystem/xing.png',
    width: 100,
    height: 100,
  },
  {
    name: 'Something',
    imgSrc: '/images/ecosystem/something.png',
    width: 113,
    height: 100,
  },
  {
    name: 'IT 桔子',
    imgSrc: '/images/ecosystem/itjuzi.png',
    width: 269,
    height: 100,
  },
  {
    name: '铅笔道',
    imgSrc: '/images/ecosystem/pencil-never-lies.png',
    width: 330,
    height: 100,
  },
  {
    name: 'CCTV 中国中央电视台',
    imgSrc: '/images/ecosystem/cctv.png',
    width: 276,
    height: 100,
  },
  {
    name: '中国新闻网',
    imgSrc: '/images/ecosystem/china-news.png',
    width: 340,
    height: 100,
  },
  {
    name: '中国青年网',
    imgSrc: '/images/ecosystem/youth.cn.png',
    width: 181,
    height: 100,
  },
  {
    name: 'Scrat 3D',
    imgSrc: '/images/ecosystem/scrat-3d.png',
    width: 341,
    height: 100,
  },
  {
    name: '智造未来',
    imgSrc: '/images/ecosystem/future-wise.png',
    width: 100,
    height: 100,
  },
  {
    name: '一念星球',
    imgSrc: '/images/ecosystem/mindful-planet.png',
    width: 306,
    height: 100,
  },
  {
    name: '图灵教育',
    imgSrc: '/images/ecosystem/turing.png',
    width: 164,
    height: 100,
  },
  {
    name: '机器之心',
    imgSrc: '/images/ecosystem/synced.png',
    width: 500,
    height: 100,
  },
  {
    name: '智咖时代',
    imgSrc: '/images/ecosystem/intelli-coffee.png',
    width: 407,
    height: 100,
  },
  {
    name: 'something2',
    imgSrc: '/images/ecosystem/something2.png',
    width: 88,
    height: 100,
  },
  {
    name: '启迪之星',
    imgSrc: '/images/ecosystem/tusstar.png',
    width: 210,
    height: 100,
  },
  {
    name: '睿尔曼智能',
    imgSrc: '/images/ecosystem/realman.png',
    width: 384,
    height: 100,
  },
  {
    name: '中科银河芯',
    imgSrc: '/images/ecosystem/gxcas.png',
    width: 351,
    height: 100,
  },
  {
    name: '吴晓波频道',
    imgSrc: '/images/ecosystem/channel-wu.png',
    width: 170,
    height: 100,
  },
  {
    name: '新菁集团',
    imgSrc: '/images/ecosystem/xin-jing.png',
    width: 380,
    height: 100,
  },
  {
    name: '中央美术学院',
    imgSrc: '/images/ecosystem/ccafa.png',
    width: 110,
    height: 100,
  },
  {
    name: '光启景明',
    imgSrc: '/images/ecosystem/guangqijingming.png',
    width: 144,
    height: 100,
  },
  {
    name: '乘方大数据',
    imgSrc: '/images/ecosystem/chengfang-logo.png',
    width: 100,
    height: 100,
  },
  {
    name: 'CSDN',
    imgSrc: '/images/ecosystem/csdn.png',
    width: 340,
    height: 100,
  },
  {
    name: 'Luobot',
    imgSrc: '/images/ecosystem/luobot.png',
    width: 358,
    height: 100,
  }
]